version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: ticket-postgres
    environment:
      POSTGRES_DB: ticketdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: ticket-redis
    ports:
      - "6380:6379" 
    command: redis-server --appendonly yes

  app:
    image: maven:3.9.2-eclipse-temurin-17
    container_name: ticket-app
    working_dir: /app
    volumes:
      - .:/app
    command: mvn spring-boot:run -Dspring-boot.run.jvmArguments="-Dspring.profiles.active=dev"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

volumes:
  pgdata: